
[browser]
gatherUsageStats = false

[global]
developmentMode = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#00ff41"
backgroundColor = "#11141a"
secondaryBackgroundColor = "#23272f"
textColor = "#f5f6fa"
font = "sans serif"
